name: Update sponsors

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update README and create PR
      uses: pawamoy/readme-sponsors@main
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}
      with:
        logo-data-source: https://pawamoy.github.io/sponsors-logo.json
